[package]
name = "ratrod"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
cbindgen = "0.28.0"

[dependencies]
libc = "0.2.171"

[lints.clippy]
missing_safety_doc = "allow"
